### ISSUE TITLE
功能建议：添加随机的验证码效果

### ISSUE THREAD

**Issue by 7890qwaszx** [pojianbing/LazyCaptcha#2]
功能建议：
验证码的形式不固定，效果随机

e.g.
动图和静态图随机出现
CaptchaType随机，例如数学运算形式的验证码和普通文本验证码随机出现

**Comment by pojianbing** [comment]
[参照最新示例](https://github.com/pojianbing/LazyCaptcha#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%9A%8F%E6%9C%BA%E9%AA%8C%E8%AF%81%E7%A0%81%E9%9C%80%E8%A6%81%E7%89%88%E6%9C%AC112)
