### ISSUE TITLE
建议字体按需加载

### ISSUE THREAD

**Issue by coolqingcheng** [pojianbing/LazyCaptcha#5]
目前中文字体包，一个都是15m，如果只用英文验证码的话，相当于浪费了内存了。
或者给一个配置，让自己决定加载哪些字体

**Comment by pojianbing** [comment]
打包在一起易用性好一点。

**Comment by wosperry** [comment]
为了易用的话，感觉可以默认全开，但是允许指定关，就可以满足了~

**Comment by pojianbing** [comment]
@coolqingcheng 
2.0.4裁剪了字体文件大小.现在dll大小不超过1M。
