### ISSUE TITLE
算术验证码按要求使用字体，不显示=？

### ISSUE THREAD

**Issue by zgssi** [pojianbing/LazyCaptcha#7]
![image](https://github.com/pojianbing/LazyCaptcha/assets/93120825/ce85f1f5-3a7a-4d40-b2fd-e7e98cc8f623)
![image](https://github.com/pojianbing/LazyCaptcha/assets/93120825/dbd4c59d-25a0-434f-8b20-8e115398797b)

**Comment by pojianbing** [comment]
2.0.6版本去除了，具体原因参考： https://gitee.com/pojianbing/lazy-captcha/pulls/11
文档和示例暂时没有更新。

**Comment by John0King** [comment]
@pojianbing  能不能配置出来？  没有 = ？  ， 数字运算的验证码很容易让人误会
