### ISSUE TITLE
可以只生成验证码，不使用存储吗？

### ISSUE THREAD

**Issue by coolqingcheng** [pojianbing/LazyCaptcha#8]
或者说，生成验证码的时候，给一个参数也行

**Comment by pojianbing** [comment]
文档常见问题里有回答的，参考下这个： https://gitee.com/pojianbing/lazy-captcha/issues/I6KXBL

**Comment by wosperry** [comment]
> 或者说，生成验证码的时候，给一个参数也行

肯定有存储的，因为你通过请求生成了一个，验证需要找到这个。
如果你不配置其他存储的话，用的就是内存cache，可能会丢失，但是这个业务不重要丢失了就刷新重新生成一个问题不大。
